org: fawwaz
app: debug-node-canvas
service: debug-node-canvas

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  createImage:
    handler: handler.createImage
    events:
      - http:
          path: /
          method: post
